spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/stomp
    username: flisoch
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
